version: "3.9"

services:
  backend:
    command: sh -c "./scripts/dev.sh"
    volumes:
      - ./backend:/backend
  frontend:
    volumes:
      - static-files:/frontend/sky_lectures/static
      - ./frontend:/frontend
      - /frontend/node_modules
