version: "3.9"

services:
  db:
    image: postgres:13
    container_name: skylectures-db
    env_file:
      - dev.env
    restart: always
    volumes:
      - /var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - dev.env
    container_name: skylectures-backend
    image: skylectures_backend
    restart: always
    volumes:
      - static-files:/backend/sky_lectures/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: skylectures-frontend
    restart: always
    volumes:
      - static-files:/frontend/sky_lectures/static
      - /frontend/node_modules
    ports:
      - 3000:3000
  nginx:
    container_name: skylectures-nginx
    build: ./nginx
    image: skylectures_nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
    volumes:
      - static-files:/backend/sky_lectures/static
  redis:
    container_name: skylectures-redis
    image: redis:latest
  celery:
    restart: always
    build: ./backend
    container_name: skylectures-celery
    command: celery -A sky_lectures worker -l info
    env_file:
      - dev.env
    depends_on:
      - db
      - redis
      - backend

volumes:
  static-files:
