# Generated by Django 3.2.6 on 2021-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ends_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
