# Generated by Django 3.2.6 on 2021-09-01 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presentation', '0001_squashed_0007_alter_presentation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='presentations', to='presentation.Tag'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to=settings.AUTH_USER_MODEL),
        ),
    ]
