# Generated by Django 3.2.6 on 2021-09-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_auto_20210901_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='tags',
            field=models.ManyToManyField(related_name='presentations', to='presentation.Tag'),
        ),
    ]
