# Generated by Django 3.2.6 on 2021-09-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_auto_20210901_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
