# Generated by Django 3.2.6 on 2021-09-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_presentations',
            field=models.ManyToManyField(blank=True, related_name='favourite_presentations', to='presentation.Presentation'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_tags',
            field=models.ManyToManyField(blank=True, related_name='favourite_tags', to='presentation.Tag'),
        ),
    ]
